AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Synvya for Restaurants - API

Parameters:
  UploadSecretArn:
    Type: String
    Description: ARN of the Secrets Manager secret containing the NIP-98 upload nsec.
  UploadSecretKey:
    Type: String
    Default: synvya-nsec
    Description: Optional key within the secret JSON that stores the nsec.
  AllowedOrigins:
    Type: CommaDelimitedList
    Default: "*"
    Description: Comma separated list of allowed origins for CORS.
  SquareEnvironment:
    Type: String
    Default: sandbox
    AllowedValues:
      - production
      - sandbox
    Description: Square environment to use for API calls.
  SquareApplicationId:
    Type: String
    Description: Square OAuth application ID.
  SquareClientSecret:
    Type: String
    Default: ""
    Description: Optional Square OAuth client secret (required for token refresh in some accounts).
  SquareRedirectUri:
    Type: String
    Description: Redirect URI configured in Square for OAuth callbacks.
  SquareVersion:
    Type: String
    Default: "2025-01-23"
    Description: Square API version header.
  GitHubTokenSecretArn:
    Type: String
    Description: ARN of the Secrets Manager secret containing the GitHub PAT for website repo.
  GitHubTokenSecretKey:
    Type: String
    Default: github-token
    Description: Optional key within the secret JSON that stores the GitHub token.

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 10
    MemorySize: 256
    Handler: handler.handler
    Environment:
      Variables:
        UPLOAD_SECRET_ARN: !Ref UploadSecretArn
        UPLOAD_SECRET_KEY: !Ref UploadSecretKey
        CORS_ALLOW_ORIGIN: !Join [",", !Ref AllowedOrigins]
    Architectures:
      - arm64

Resources:
  UploadApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins: !Ref AllowedOrigins
        AllowHeaders:
          - "*"
        AllowMethods:
          - OPTIONS
          - GET
          - POST

  UploadProxyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: media.handler
      CodeUri: lambda/
      Description: Proxies NIP-96 uploads to nostr.build, signing requests with NIP-98.
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref UploadSecretArn
      Events:
        UploadApi:
          Type: HttpApi
          Properties:
            Path: /media/upload
            Method: POST
            PayloadFormatVersion: "2.0"
            ApiId: !Ref UploadApi
  SquareConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pubkey
          AttributeType: S
      KeySchema:
        - AttributeName: pubkey
          KeyType: HASH

  CustomersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: synvya-customers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: npub
          AttributeType: S
      KeySchema:
        - AttributeName: npub
          KeyType: HASH

  SquareIntegrationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: square.handler
      Description: Handles Square OAuth exchange and catalog sync for NIP-99 listings.
      Environment:
        Variables:
          CORS_ALLOW_ORIGIN: !Join [",", !Ref AllowedOrigins]
          SQUARE_CONNECTIONS_TABLE: !Ref SquareConnectionsTable
          SQUARE_ENV: !Ref SquareEnvironment
          SQUARE_APPLICATION_ID: !Ref SquareApplicationId
          SQUARE_CLIENT_SECRET: !Ref SquareClientSecret
          SQUARE_REDIRECT_URI: !Ref SquareRedirectUri
          SQUARE_VERSION: !Ref SquareVersion
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SquareConnectionsTable
      Events:
        Status:
          Type: HttpApi
          Properties:
            Path: /square/status
            Method: GET
            PayloadFormatVersion: "2.0"
            ApiId: !Ref UploadApi
        Exchange:
          Type: HttpApi
          Properties:
            Path: /square/oauth/exchange
            Method: POST
            PayloadFormatVersion: "2.0"
            ApiId: !Ref UploadApi
        Preview:
          Type: HttpApi
          Properties:
            Path: /square/preview
            Method: POST
            PayloadFormatVersion: "2.0"
            ApiId: !Ref UploadApi
        Publish:
          Type: HttpApi
          Properties:
            Path: /square/publish
            Method: POST
            PayloadFormatVersion: "2.0"
            ApiId: !Ref UploadApi

  CustomerRegistryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: synvya-customer-registry
      CodeUri: lambda/
      Handler: customers.handler
      Description: Handles customer registration and reservation tracking.
      Environment:
        Variables:
          CORS_ALLOW_ORIGIN: !Join [",", !Ref AllowedOrigins]
          CUSTOMERS_TABLE: !Ref CustomersTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CustomersTable
      Events:
        Register:
          Type: HttpApi
          Properties:
            Path: /api/customers/register
            Method: POST
            PayloadFormatVersion: "2.0"
            ApiId: !Ref UploadApi
        Reservations:
          Type: HttpApi
          Properties:
            Path: /api/customers/reservations
            Method: POST
            PayloadFormatVersion: "2.0"
            ApiId: !Ref UploadApi

  BotAnalyticsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: synvya-bot-analytics
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: npub
          AttributeType: S
        - AttributeName: dateBotKey
          AttributeType: S
      KeySchema:
        - AttributeName: npub
          KeyType: HASH
        - AttributeName: dateBotKey
          KeyType: RANGE

  BotAnalyticsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: synvya-bot-analytics-api
      CodeUri: lambda/
      Handler: analytics.handler
      Description: Serves bot analytics data for merchant discovery pages.
      Environment:
        Variables:
          CORS_ALLOW_ORIGIN: !Join [",", !Ref AllowedOrigins]
          BOT_ANALYTICS_TABLE: !Ref BotAnalyticsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BotAnalyticsTable
      Events:
        GetAnalytics:
          Type: HttpApi
          Properties:
            Path: /analytics/{npub}
            Method: GET
            PayloadFormatVersion: "2.0"
            ApiId: !Ref UploadApi

  DiscoveryPublishFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: synvya-discovery-publish
      CodeUri: lambda/
      Handler: discovery.handler
      Description: Publishes discovery pages to synvya.com via GitHub workflow.
      Environment:
        Variables:
          CORS_ALLOW_ORIGIN: !Join [",", !Ref AllowedOrigins]
          GITHUB_TOKEN_SECRET_ARN: !Ref GitHubTokenSecretArn
          GITHUB_TOKEN_SECRET_KEY: !Ref GitHubTokenSecretKey
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref GitHubTokenSecretArn
      Events:
        Publish:
          Type: HttpApi
          Properties:
            Path: /discovery/publish
            Method: POST
            PayloadFormatVersion: "2.0"
            ApiId: !Ref UploadApi

Outputs:
  ApiBaseUrl:
    Description: Base URL for the Synvya for Restaurants API.
    Value: !Sub "https://${UploadApi}.execute-api.${AWS::Region}.amazonaws.com"
  UploadProxyEndpoint:
    Description: API Gateway endpoint for the upload proxy.
    Value: !Sub "https://${UploadApi}.execute-api.${AWS::Region}.amazonaws.com/media/upload"
  DiscoveryPublishEndpoint:
    Description: API Gateway endpoint for publishing discovery pages.
    Value: !Sub "https://${UploadApi}.execute-api.${AWS::Region}.amazonaws.com/discovery/publish"
